// All the game's data: who you can be, what you can cast, what wants you
// dead, what it drops, and the five acts of Prussia you cross to end it.

import { hex, PAL } from '../render/palette.js';

// ---------------------------------------------------------------------------
// Appearance definitions (fed to render/actors.js)
// ---------------------------------------------------------------------------

const skinTones = {
  skin: hex('#c29c7e'),
  skinLight: hex('#e2c3a2'),
  skinDark: hex('#6f513c'),
};

export const LOOKS = {
  ritter: {
    plan: 'humanoid',
    helm: 'greathelm',
    torso: 'surcoat',
    weapon: 'sword',
    offhand: 'shield',
    cape: true,
    pauldrons: true,
    weaponHand: 'R',
    weaponLen: 44,
    capeLen: 48,
    headR: 7.8,
    // The Order's white, pitched dark on purpose. A torch is multiplied over
    // these before you see them, and a linen that starts near-white ends up a
    // blown-out cream slab with no cross visible on it. Starting at a dirty
    // grey leaves the light somewhere to go, and keeps the black cross
    // readable — which is the whole silhouette.
    capeColor: hex('#8e8a7d'),
    capeColorLight: hex('#c3bfb1'),
    capeColorDark: hex('#3c3b36'),
    shieldColor: hex('#9d998c'),
    shieldLight: hex('#cbc7ba'),
    shieldDark: hex('#43423c'),
    shieldEmblem: PAL.orderBlack,
    rim: hex('#cfd6dc'),
    colors: {
      torso: hex('#979283'),
      torsoLight: hex('#cbc7b8'),
      torsoDark: hex('#43423b'),
      arms: hex('#78808d'),
      armsLight: hex('#c0c8d4'),
      armsDark: hex('#333943'),
      legs: hex('#68707c'),
      legsLight: hex('#a4adb9'),
      legsDark: hex('#2c3138'),
      boots: hex('#382c20'),
      metal: hex('#8a94a3'),
      metalDark: hex('#3b424e'),
      metalLight: hex('#d3dbe6'),
      belt: hex('#38281a'),
      emblem: PAL.orderBlack,
      ...skinTones,
    },
  },
  jaegerin: {
    plan: 'humanoid',
    helm: 'hood',
    torso: 'fur',
    weapon: 'bow',
    offhand: 'none',
    // A short travelling cloak: without it the silhouette reads as a slab.
    cape: true,
    capeLen: 28,
    capeColor: hex('#232a1c'),
    capeColorLight: hex('#3c4630'),
    capeColorDark: hex('#0e120b'),
    weaponHand: 'L',
    weaponLen: 40,
    headR: 7.4,
    hood: hex('#3a4632'),
    hoodLight: hex('#67784f'),
    rim: hex('#9fd0a8'),
    colors: {
      torso: hex('#40351f'),
      torsoLight: hex('#6a5738'),
      torsoDark: hex('#1c1710'),
      arms: hex('#8b7053'),
      armsLight: hex('#c0a081'),
      armsDark: hex('#3e3122'),
      legs: hex('#4c4232'),
      legsLight: hex('#7c6e54'),
      legsDark: hex('#241f16'),
      boots: hex('#31261a'),
      metal: hex('#7d8590'),
      metalDark: hex('#343a42'),
      metalLight: hex('#c4ccd6'),
      belt: hex('#2e2316'),
      ...skinTones,
    },
  },
  hexer: {
    plan: 'humanoid',
    helm: 'none',
    hair: hex('#2b2118'),
    torso: 'robe',
    weapon: 'staff',
    offhand: 'orb',
    cape: true,
    weaponHand: 'R',
    weaponLen: 54,
    capeLen: 54,
    headR: 7.4,
    gem: PAL.amber,
    capeColor: hex('#4a3a58'),
    capeColorLight: hex('#75608a'),
    capeColorDark: hex('#221a2c'),
    rim: hex('#ffd08a'),
    colors: {
      torso: hex('#4e4058'),
      torsoLight: hex('#7a6688'),
      torsoDark: hex('#231b2b'),
      arms: hex('#b8916f'),
      armsLight: hex('#e0bd97'),
      armsDark: hex('#664a35'),
      legs: hex('#3a3044'),
      legsLight: hex('#5e5070'),
      legsDark: hex('#1b1521'),
      boots: hex('#2a2118'),
      metal: hex('#8a94a3'),
      metalDark: hex('#3b424e'),
      metalLight: hex('#d3dbe6'),
      belt: hex('#4a3520'),
      ...skinTones,
    },
  },
};

const mob = (o) => ({ plan: 'humanoid', headR: 7.2, ...o });

export const MOB_LOOKS = {
  drowned: mob({
    helm: 'none',
    hair: hex('#243036'),
    torso: 'fur',
    weapon: 'none',
    glowEyes: hex('#6fd3d0'),
    rim: hex('#8fd6e8'),
    limbScale: 1.05,
    colors: {
      torso: hex('#3c4a4a'),
      torsoLight: hex('#63797a'),
      torsoDark: hex('#161f21'),
      arms: hex('#6d8079'),
      armsLight: hex('#9db3a8'),
      armsDark: hex('#2c3a37'),
      legs: hex('#5c6d68'),
      legsLight: hex('#8ba098'),
      legsDark: hex('#232e2c'),
      boots: hex('#20282a'),
      metal: hex('#6b7480'),
      metalDark: hex('#2b3138'),
      metalLight: hex('#a9b3c0'),
      skin: hex('#7e9a90'),
      skinLight: hex('#a8c4b8'),
      skinDark: hex('#3a4a46'),
      belt: hex('#22201a'),
    },
  }),
  crabling: mob({
    plan: 'humanoid',
    helm: 'none',
    torso: 'bare',
    weapon: 'claw',
    weaponLen: 26,
    limbScale: 1.25,
    headR: 6,
    glowEyes: hex('#ffca6a'),
    rim: hex('#ffbb77'),
    build: { hipH: 30, chestH: 46, neckH: 53, headH: 60, thigh: 16, shin: 15, upperArm: 16, foreArm: 15 },
    colors: {
      torso: hex('#7a4a2c'),
      torsoLight: hex('#b0724a'),
      torsoDark: hex('#341d10'),
      arms: hex('#8c5632'),
      armsLight: hex('#c07f4e'),
      armsDark: hex('#3c2312'),
      legs: hex('#6a3f24'),
      legsLight: hex('#9a6440'),
      legsDark: hex('#2c1a0e'),
      boots: hex('#241408'),
      metal: hex('#7d8590'),
      metalDark: hex('#343a42'),
      metalLight: hex('#c4ccd6'),
      skin: hex('#8c5632'),
      skinLight: hex('#c07f4e'),
      skinDark: hex('#3c2312'),
      belt: hex('#241408'),
    },
  }),
  raider: mob({
    helm: 'horned',
    torso: 'fur',
    weapon: 'axe',
    weaponLen: 34,
    rim: hex('#ffcf9a'),
    colors: {
      torso: hex('#5a4630'),
      torsoLight: hex('#8a6d49'),
      torsoDark: hex('#281e14'),
      arms: hex('#a07b58'),
      armsLight: hex('#d0a87e'),
      armsDark: hex('#4a3624'),
      legs: hex('#4a3c2c'),
      legsLight: hex('#786349'),
      legsDark: hex('#221b13'),
      boots: hex('#2c2116'),
      metal: hex('#79808b'),
      metalDark: hex('#31363d'),
      metalLight: hex('#bcc4ce'),
      belt: hex('#33251a'),
      ...skinTones,
    },
  }),
  shaman: mob({
    helm: 'hood',
    torso: 'robe',
    weapon: 'staff',
    offhand: 'orb',
    weaponLen: 46,
    cape: true,
    gem: PAL.bogfire,
    glowEyes: PAL.bogfire,
    hood: hex('#2f3a2c'),
    hoodLight: hex('#54664a'),
    capeColor: hex('#39442f'),
    capeColorLight: hex('#5d6c4b'),
    capeColorDark: hex('#1a2015'),
    rim: PAL.bogfire,
    colors: {
      torso: hex('#3d4a33'),
      torsoLight: hex('#65754f'),
      torsoDark: hex('#1a2015'),
      arms: hex('#9c8060'),
      armsLight: hex('#c7a883'),
      armsDark: hex('#473828'),
      legs: hex('#333d2b'),
      legsLight: hex('#57654a'),
      legsDark: hex('#161a11'),
      boots: hex('#241c12'),
      metal: hex('#79808b'),
      metalDark: hex('#31363d'),
      metalLight: hex('#bcc4ce'),
      belt: hex('#2b2116'),
      ...skinTones,
    },
  }),
  wolf: {
    plan: 'quadruped',
    shaggy: true,
    glowEyes: hex('#ffd06a'),
    rim: hex('#cfe0ff'),
    build: { bodyLen: 40, bodyH: 40, legLen: 30, headFwd: 32, headH: 46 },
    colors: {
      torso: hex('#4a4237'),
      torsoLight: hex('#7d7462'),
      torsoDark: hex('#1f1b16'),
      legs: hex('#3e372e'),
      legsLight: hex('#6a6154'),
      legsDark: hex('#191612'),
    },
  },
  direwolf: {
    plan: 'quadruped',
    shaggy: true,
    glowEyes: hex('#ff6a3c'),
    rim: hex('#ffb07a'),
    build: { bodyLen: 52, bodyH: 52, legLen: 40, headFwd: 42, headH: 60 },
    colors: {
      torso: hex('#2e2a26'),
      torsoLight: hex('#5c5449'),
      torsoDark: hex('#131110'),
      legs: hex('#282420'),
      legsLight: hex('#4c453c'),
      legsDark: hex('#0f0d0c'),
    },
  },
  wraith: {
    plan: 'wraith',
    ghostly: true,
    glowEyes: PAL.bogfire,
    build: { height: 96 },
    colors: {
      torso: hex('#33474a'),
      torsoLight: hex('#6d8a86'),
      torsoDark: hex('#101a1c'),
      legs: hex('#9fb8b0'),
    },
  },
  laume: {
    plan: 'wraith',
    ghostly: true,
    glowEyes: hex('#a8ffe0'),
    build: { height: 150 },
    colors: {
      torso: hex('#2a4a48'),
      torsoLight: hex('#79b8a8'),
      torsoDark: hex('#0c1618'),
      legs: hex('#c0efe0'),
    },
  },
  skeleton: mob({
    helm: 'skull',
    torso: 'mail',
    weapon: 'sword',
    offhand: 'shield',
    weaponLen: 36,
    glowEyes: hex('#8fd6ff'),
    rim: hex('#bcd8ff'),
    shieldColor: hex('#6a6558'),
    shieldLight: hex('#8f8a7c'),
    shieldDark: hex('#33302a'),
    shieldEmblem: hex('#1a1a1e'),
    colors: {
      torso: hex('#48484f'),
      torsoLight: hex('#7a7a84'),
      torsoDark: hex('#1c1c21'),
      arms: hex('#c4b99f'),
      armsLight: hex('#e0d6be'),
      armsDark: hex('#6a6250'),
      legs: hex('#bcb197'),
      legsLight: hex('#d8ceb6'),
      legsDark: hex('#615a4a'),
      boots: hex('#2a241c'),
      metal: hex('#7d8590'),
      metalDark: hex('#343a42'),
      metalLight: hex('#c4ccd6'),
      skin: hex('#ded3ba'),
      skinLight: hex('#f0e8d4'),
      skinDark: hex('#8d8267'),
      belt: hex('#2e2316'),
    },
  }),
  crossbowman: mob({
    helm: 'kettle',
    torso: 'mail',
    weapon: 'bow',
    weaponLen: 36,
    weaponHand: 'L',
    glowEyes: hex('#8fd6ff'),
    rim: hex('#bcd8ff'),
    colors: {
      torso: hex('#4c4c54'),
      torsoLight: hex('#7f7f8a'),
      torsoDark: hex('#1e1e24'),
      arms: hex('#c4b99f'),
      armsLight: hex('#e0d6be'),
      armsDark: hex('#6a6250'),
      legs: hex('#b4a992'),
      legsLight: hex('#d0c6ae'),
      legsDark: hex('#595242'),
      boots: hex('#2a241c'),
      metal: hex('#828a95'),
      metalDark: hex('#363c44'),
      metalLight: hex('#c8d0da'),
      skin: hex('#ded3ba'),
      skinLight: hex('#f0e8d4'),
      skinDark: hex('#8d8267'),
      belt: hex('#2e2316'),
    },
  }),
  knightRevenant: mob({
    helm: 'greathelm',
    torso: 'plate',
    weapon: 'greatsword',
    weaponLen: 46,
    cape: true,
    pauldrons: true,
    glowEyes: hex('#ff7a4a'),
    rim: hex('#ffb27a'),
    capeColor: hex('#5a5347'),
    capeColorLight: hex('#8a8172'),
    capeColorDark: hex('#221f19'),
    limbScale: 1.12,
    colors: {
      torso: hex('#5c5c62'),
      torsoLight: hex('#95959e'),
      torsoDark: hex('#23232a'),
      arms: hex('#585d66'),
      armsLight: hex('#90959f'),
      armsDark: hex('#22252b'),
      legs: hex('#4e535b'),
      legsLight: hex('#828892'),
      legsDark: hex('#1d2025'),
      boots: hex('#2a241c'),
      metal: hex('#767f8b'),
      metalDark: hex('#2f353d'),
      metalLight: hex('#bfc8d4'),
      skin: hex('#9a958a'),
      skinLight: hex('#c0bbb0'),
      skinDark: hex('#4a4740'),
      belt: hex('#2e2316'),
    },
  }),
  amberGiant: mob({
    helm: 'horned',
    torso: 'plate',
    pauldrons: true,
    weapon: 'mace',
    weaponLen: 54,
    limbScale: 1.5,
    headR: 9,
    glowEyes: PAL.amber,
    rim: PAL.amber,
    build: { hipH: 58, chestH: 88, neckH: 100, headH: 112, shoulderW: 20, hipW: 13, thigh: 30, shin: 28, upperArm: 26, foreArm: 24 },
    colors: {
      torso: hex('#54371a'),
      torsoLight: hex('#9a6c28'),
      torsoDark: hex('#20140a'),
      arms: hex('#603f1d'),
      armsLight: hex('#a4772f'),
      armsDark: hex('#261805'),
      legs: hex('#5e4220'),
      legsLight: hex('#a2762f'),
      legsDark: hex('#241806'),
      boots: hex('#1c1206'),
      metal: hex('#8a7a4a'),
      metalDark: hex('#3a3018'),
      metalLight: hex('#d8c07a'),
      skin: hex('#8a6428'),
      skinLight: hex('#d4a04a'),
      skinDark: hex('#3a2810'),
      belt: hex('#2a1c0c'),
    },
  }),
  perkunas: mob({
    helm: 'horned',
    torso: 'plate',
    weapon: 'mace',
    weaponLen: 58,
    cape: true,
    pauldrons: true,
    limbScale: 1.45,
    headR: 9,
    glowEyes: PAL.thunder,
    rim: PAL.thunder,
    // Storm-iron, kept dark on purpose: the figure is read by the rim light
    // and the sigils burning through the plate, not by its own value.
    runes: { color: hex('#a8ccff'), glow: 0.6 },
    weaponGlow: hex('#bcd8ff'),
    capeColor: hex('#2b2140'),
    capeColorLight: hex('#4c3d70'),
    capeColorDark: hex('#100b1c'),
    build: { hipH: 56, chestH: 86, neckH: 98, headH: 110, shoulderW: 19, hipW: 12, thigh: 29, shin: 27, upperArm: 25, foreArm: 23 },
    colors: {
      torso: hex('#2b2740'),
      torsoLight: hex('#584f7a'),
      torsoDark: hex('#100d1a'),
      arms: hex('#2e2942'),
      armsLight: hex('#5b5180'),
      armsDark: hex('#120f1c'),
      legs: hex('#262238'),
      legsLight: hex('#4d4570'),
      legsDark: hex('#0d0b16'),
      boots: hex('#120e1a'),
      metal: hex('#5f5a80'),
      metalDark: hex('#241f34'),
      metalLight: hex('#b3aad4'),
      skin: hex('#5d5680'),
      skinLight: hex('#8f86b4'),
      skinDark: hex('#2a2540'),
      belt: hex('#1c1728'),
    },
  }),
};

// ---------------------------------------------------------------------------
// Classes
// ---------------------------------------------------------------------------

export const CLASSES = {
  ritter: {
    id: 'ritter',
    name: 'Орденский рыцарь',
    subtitle: 'Брат Тевтонского ордена',
    blurb:
      'Schwert und Schild. Er hält die Linie, wo andere fallen — und sein Zorn wächst mit jedem Hieb.',
    look: 'ritter',
    resource: { id: 'zorn', name: 'Ярость', color: hex('#d24a2a'), max: 100, regen: -4, onHit: 9, onTakeHit: 6 },
    base: { might: 12, agility: 7, vigor: 12, spirit: 5, life: 150, armor: 14, moveSpeed: 176 },
    perLevel: { might: 2.4, agility: 1.1, vigor: 2.6, spirit: 0.7, life: 22, armor: 2.1 },
    weaponDmg: [9, 14],
    skills: ['kreuzhieb', 'schildsturm', 'bannkreis', 'ordenszorn'],
    critChance: 0.06,
  },
  jaegerin: {
    id: 'jaegerin',
    name: 'Охотница',
    subtitle: 'Прусская следопытка',
    blurb: 'Sie kennt jeden Pfad der Rominter Heide. Was sie sieht, ist bereits tot.',
    look: 'jaegerin',
    resource: { id: 'atem', name: 'Дыхание', color: hex('#4ad2a0'), max: 100, regen: 15, onHit: 0, onTakeHit: 0 },
    base: { might: 8, agility: 13, vigor: 8, spirit: 7, life: 118, armor: 8, moveSpeed: 196 },
    perLevel: { might: 1.2, agility: 2.7, vigor: 1.7, spirit: 1.2, life: 16, armor: 1.3 },
    weaponDmg: [7, 17],
    skills: ['schnellschuss', 'wolfsfalle', 'pfeilhagel', 'schattenschritt'],
    critChance: 0.12,
  },
  hexer: {
    id: 'hexer',
    name: 'Янтарный колдун',
    subtitle: 'Дитя старых богов',
    blurb: 'Bernstein ist geronnenes Sonnenlicht. Er hat gelernt, es wieder brennen zu lassen.',
    look: 'hexer',
    resource: { id: 'mana', name: 'Мана', color: hex('#4a9ad2'), max: 110, regen: 11, onHit: 0, onTakeHit: 0 },
    base: { might: 6, agility: 8, vigor: 8, spirit: 14, life: 112, armor: 6, moveSpeed: 184 },
    perLevel: { might: 0.9, agility: 1.3, vigor: 1.7, spirit: 2.9, life: 15, armor: 1.1 },
    weaponDmg: [6, 12],
    skills: ['bernsteinsplitter', 'frostatem', 'donnerkeil', 'bernsteinwall'],
    critChance: 0.08,
  },
};

// ---------------------------------------------------------------------------
// Skills
// ---------------------------------------------------------------------------

export const SKILLS = {
  // -- Ordensritter ---------------------------------------------------------
  kreuzhieb: {
    id: 'kreuzhieb',
    name: 'Крестовый удар',
    desc: 'Широкий взмах меча перед собой. Даёт ярость.',
    kind: 'melee',
    icon: 'slash',
    cost: 0,
    cd: 0.42,
    anim: 'attack',
    windup: 0.19,
    arc: 1.15,
    range: 84,
    coef: 1.0,
    knock: 90,
    color: hex('#e8e2d0'),
    gain: 9,
    unlock: 1,
  },
  schildsturm: {
    id: 'schildsturm',
    name: 'Натиск щитом',
    desc: 'Бросок вперёд: сбивает всё с ног и оглушает.',
    kind: 'dashAttack',
    icon: 'shield',
    cost: 22,
    cd: 6.5,
    anim: 'dash',
    dashDist: 250,
    dashTime: 0.3,
    radius: 62,
    coef: 1.5,
    knock: 300,
    stun: 1.5,
    color: hex('#cfe0ff'),
    unlock: 2,
  },
  bannkreis: {
    id: 'bannkreis',
    name: 'Круг заклятия',
    desc: 'Освящённая земля. Жжёт нежить и лечит тебя, пока ты стоишь в круге.',
    kind: 'ground',
    icon: 'circle',
    cost: 30,
    cd: 11,
    anim: 'cast',
    radius: 150,
    duration: 7,
    tick: 0.5,
    coef: 0.34,
    heal: 0.016,
    color: PAL.holy,
    unlock: 5,
  },
  ordenszorn: {
    id: 'ordenszorn',
    name: 'Гнев Ордена',
    desc: 'Закрути меч и разорви всё вокруг.',
    kind: 'channel',
    icon: 'whirl',
    cost: 12,
    costPerSec: 26,
    cd: 1.2,
    anim: 'attack',
    radius: 108,
    tick: 0.2,
    coef: 0.5,
    knock: 60,
    color: hex('#ffcf9a'),
    unlock: 9,
  },

  // -- Jägerin --------------------------------------------------------------
  schnellschuss: {
    id: 'schnellschuss',
    name: 'Быстрый выстрел',
    desc: 'Стрела, проходящая насквозь.',
    kind: 'projectile',
    icon: 'arrow',
    cost: 0,
    cd: 0.36,
    anim: 'thrust',
    windup: 0.14,
    speed: 900,
    range: 620,
    coef: 1.05,
    pierce: 2,
    radius: 11,
    color: hex('#e8dfae'),
    unlock: 1,
  },
  wolfsfalle: {
    id: 'wolfsfalle',
    name: 'Волчий капкан',
    desc: 'Железные зубы в листве. Держит и грызёт.',
    kind: 'trap',
    icon: 'trap',
    cost: 20,
    cd: 7,
    anim: 'cast',
    radius: 66,
    duration: 22,
    coef: 2.2,
    root: 2.2,
    color: hex('#b9c3cf'),
    unlock: 2,
  },
  pfeilhagel: {
    id: 'pfeilhagel',
    name: 'Град стрел',
    desc: 'Дождь стрел над местом, что ты выберешь.',
    kind: 'rain',
    icon: 'rain',
    cost: 34,
    cd: 9,
    anim: 'cast',
    radius: 140,
    duration: 3.2,
    tick: 0.22,
    coef: 0.3,
    color: hex('#dccf9a'),
    unlock: 5,
  },
  schattenschritt: {
    id: 'schattenschritt',
    name: 'Шаг сквозь тень',
    desc: 'Исчезни и возникни у них за спиной — с натянутым луком.',
    kind: 'blink',
    icon: 'blink',
    cost: 26,
    cd: 6,
    dist: 260,
    volley: 5,
    coef: 0.55,
    color: hex('#7fe0c0'),
    unlock: 9,
  },

  // -- Bernsteinhexer -------------------------------------------------------
  bernsteinsplitter: {
    id: 'bernsteinsplitter',
    name: 'Янтарные осколки',
    desc: 'Три осколка раскалённого янтаря.',
    kind: 'projectile',
    icon: 'shard',
    cost: 0,
    cd: 0.44,
    anim: 'cast',
    windup: 0.16,
    speed: 620,
    range: 480,
    coef: 0.52,
    count: 3,
    spread: 0.24,
    radius: 13,
    color: PAL.amber,
    glow: true,
    unlock: 1,
  },
  frostatem: {
    id: 'frostatem',
    name: 'Морозное дыхание',
    desc: 'Дыхание залива. Конус льда, замедляющий всё.',
    kind: 'cone',
    icon: 'frost',
    cost: 24,
    cd: 5,
    anim: 'cast',
    arc: 0.75,
    range: 230,
    coef: 1.15,
    slow: 0.55,
    slowTime: 3.5,
    color: PAL.frost,
    glow: true,
    unlock: 2,
  },
  donnerkeil: {
    id: 'donnerkeil',
    name: 'Громовой клин',
    desc: 'Перкунас отвечает. Молния бьёт туда, куда ты укажешь.',
    kind: 'strike',
    icon: 'bolt',
    cost: 32,
    cd: 4.2,
    anim: 'cast',
    radius: 96,
    delay: 0.34,
    coef: 2.6,
    color: PAL.thunder,
    glow: true,
    unlock: 5,
  },
  bernsteinwall: {
    id: 'bernsteinwall',
    name: 'Янтарный вал',
    desc: 'Смола застывает вокруг тебя. Впитывает урон и швыряет его обратно.',
    kind: 'ward',
    icon: 'ward',
    cost: 40,
    cd: 14,
    anim: 'cast',
    duration: 8,
    absorb: 0.55,
    reflect: 0.6,
    color: PAL.amberDeep,
    glow: true,
    unlock: 9,
  },
};

// ---------------------------------------------------------------------------
// Monsters
// ---------------------------------------------------------------------------

/**
 * ai:  'melee'   walk in, swing
 *      'charger' keeps distance, then lunges
 *      'ranged'  holds range, shoots
 *      'caster'  holds range, telegraphed ground spell
 *      'swarm'   fast, weak, mobs up
 */
export const MONSTERS = {
  crabling: {
    id: 'crabling',
    name: 'Янтарный ползун',
    look: 'crabling',
    ai: 'swarm',
    size: 46,
    radius: 16,
    life: 22,
    dmg: 5,
    speed: 152,
    armor: 0,
    xp: 6,
    attackRange: 34,
    attackCd: 1.1,
    windup: 0.32,
    hitSound: 'hitBone',
  },
  drowned: {
    id: 'drowned',
    name: 'Утопший рыбак',
    look: 'drowned',
    ai: 'melee',
    size: 74,
    radius: 20,
    life: 46,
    dmg: 9,
    speed: 96,
    armor: 3,
    xp: 12,
    attackRange: 46,
    attackCd: 1.7,
    windup: 0.44,
    hitSound: 'hitFlesh',
  },
  wolf: {
    id: 'wolf',
    name: 'Пустошный волк',
    look: 'wolf',
    ai: 'charger',
    size: 62,
    radius: 20,
    life: 54,
    dmg: 11,
    speed: 208,
    armor: 2,
    xp: 15,
    attackRange: 54,
    attackCd: 1.6,
    windup: 0.34,
    lunge: 190,
    hitSound: 'hitFlesh',
    sound: 'growl',
  },
  raider: {
    id: 'raider',
    name: 'Жемайтский разбойник',
    look: 'raider',
    ai: 'melee',
    size: 78,
    radius: 21,
    life: 76,
    dmg: 14,
    speed: 132,
    armor: 7,
    xp: 22,
    attackRange: 52,
    attackCd: 1.5,
    windup: 0.4,
    hitSound: 'hitArmor',
  },
  shaman: {
    id: 'shaman',
    name: 'Вайделот',
    look: 'shaman',
    ai: 'caster',
    size: 76,
    radius: 20,
    life: 62,
    dmg: 17,
    speed: 108,
    armor: 4,
    xp: 26,
    attackRange: 320,
    attackCd: 2.8,
    windup: 0.85,
    spell: 'bogfire',
    hitSound: 'hitFlesh',
  },
  wraith: {
    id: 'wraith',
    name: 'Болотный дух',
    look: 'wraith',
    ai: 'melee',
    size: 82,
    radius: 20,
    life: 68,
    dmg: 16,
    speed: 116,
    armor: 2,
    xp: 28,
    attackRange: 58,
    attackCd: 1.9,
    windup: 0.5,
    ghostly: true,
    hitSound: 'hitFlesh',
  },
  skeleton: {
    id: 'skeleton',
    name: 'Павший брат Ордена',
    look: 'skeleton',
    ai: 'melee',
    size: 78,
    radius: 20,
    life: 92,
    dmg: 19,
    speed: 124,
    armor: 12,
    xp: 34,
    attackRange: 52,
    attackCd: 1.4,
    windup: 0.38,
    hitSound: 'hitBone',
  },
  crossbowman: {
    id: 'crossbowman',
    name: 'Мёртвый арбалетчик',
    look: 'crossbowman',
    ai: 'ranged',
    size: 76,
    radius: 20,
    life: 70,
    dmg: 22,
    speed: 104,
    armor: 8,
    xp: 36,
    attackRange: 400,
    attackCd: 2.6,
    windup: 0.7,
    projSpeed: 620,
    hitSound: 'hitBone',
  },
  revenant: {
    id: 'revenant',
    name: 'Выходец',
    look: 'knightRevenant',
    ai: 'melee',
    size: 92,
    radius: 24,
    life: 150,
    dmg: 28,
    speed: 118,
    armor: 20,
    xp: 55,
    attackRange: 62,
    attackCd: 1.7,
    windup: 0.52,
    hitSound: 'hitArmor',
  },
};

export const BOSSES = {
  bernsteinfresser: {
    id: 'bernsteinfresser',
    name: 'Янтарный пожиратель',
    title: 'То, что выплюнул залив',
    look: 'amberGiant',
    ai: 'boss',
    size: 152,
    radius: 46,
    life: 900,
    dmg: 30,
    speed: 82,
    armor: 14,
    xp: 400,
    attackRange: 100,
    attackCd: 2.4,
    windup: 0.62,
    boss: true,
    hitSound: 'hitArmor',
    abilities: ['slam', 'shards'],
    light: { color: PAL.amber, r: 300, i: 0.8 },
  },
  wolfsvater: {
    id: 'wolfsvater',
    name: 'Волчий отец',
    title: 'Владыка Роминтенской пущи',
    look: 'direwolf',
    ai: 'boss',
    size: 122,
    radius: 40,
    life: 1500,
    dmg: 36,
    speed: 196,
    armor: 16,
    xp: 700,
    attackRange: 84,
    attackCd: 1.7,
    windup: 0.36,
    lunge: 320,
    boss: true,
    hitSound: 'hitFlesh',
    abilities: ['howl', 'leap'],
    light: { color: hex('#ff6a3c'), r: 220, i: 0.5 },
  },
  laume: {
    id: 'laume',
    name: 'Лаума, мать болот',
    title: 'Она считает утопших',
    look: 'laume',
    ai: 'boss',
    size: 148,
    radius: 42,
    life: 2200,
    dmg: 40,
    speed: 104,
    armor: 14,
    xp: 1100,
    attackRange: 300,
    attackCd: 2.2,
    windup: 0.7,
    boss: true,
    ghostly: true,
    hitSound: 'hitFlesh',
    abilities: ['bogNova', 'summon'],
    light: { color: PAL.bogfire, r: 340, i: 0.9 },
  },
  hochmeister: {
    id: 'hochmeister',
    name: 'Последний великий магистр',
    title: 'Он не забыл своей клятвы',
    look: 'knightRevenant',
    ai: 'boss',
    size: 136,
    radius: 40,
    life: 2800,
    dmg: 48,
    speed: 138,
    armor: 22,
    xp: 1700,
    attackRange: 92,
    attackCd: 1.5,
    windup: 0.44,
    boss: true,
    hitSound: 'hitArmor',
    abilities: ['charge', 'swordRing', 'summon'],
    light: { color: hex('#ff7a4a'), r: 260, i: 0.7 },
  },
  perkunas: {
    id: 'perkunas',
    name: 'Перкунас',
    title: 'Гром над священным дубом',
    look: 'perkunas',
    ai: 'boss',
    size: 168,
    radius: 50,
    life: 3400,
    dmg: 58,
    speed: 126,
    armor: 26,
    xp: 3000,
    attackRange: 106,
    attackCd: 1.6,
    windup: 0.5,
    boss: true,
    hitSound: 'hitArmor',
    abilities: ['lightning', 'swordRing', 'slam', 'summon'],
    light: { color: PAL.thunder, r: 420, i: 1.0 },
  },
};

// ---------------------------------------------------------------------------
// Acts
// ---------------------------------------------------------------------------

export const ACTS = [
  {
    id: 'coast',
    name: 'I. Фришес-Гаф',
    subtitle: 'Янтарный берег на ледяном ветру',
    intro:
      'Буря выбросила когг на косу. Между янтарём и льдом что-то выползает из воды.',
    ambience: 'coast',
    key: 38,
    terrain: {
      base: 'sand',
      wet: 0.16,
      layers: [
        { mat: 'ice', scale: 0.0016, threshold: 0.12, softness: 0.3 },
        { mat: 'snow', scale: 0.0031, threshold: 0.2, softness: 0.34, offset: 31 },
      ],
    },
    props: [
      { name: 'iceFloe', w: 4 },
      { name: 'rockAmber', w: 1.1 },
      { name: 'rock', w: 6 },
      { name: 'reeds', w: 8 },
      { name: 'bones', w: 2.4 },
      { name: 'crate', w: 0.7 },
      { name: 'pineSnowy', w: 1.6 },
      { name: 'pineDead', w: 1.2 },
    ],
    landmarks: ['wreck', 'brazier'],
    monsters: ['crabling', 'crabling', 'drowned'],
    boss: 'bernsteinfresser',
    quota: 26,
    size: 2600,
    levelRange: [1, 6],
  },
  {
    id: 'forest',
    name: 'II. Роминтенская пуща',
    subtitle: 'Дремучий лес без троп',
    intro:
      'Древние сосны, а под ними жемайты, ненавидящие Орден. Здесь на обоих охотится нечто большее.',
    ambience: 'forest',
    key: 41,
    terrain: {
      base: 'moss',
      wet: 0.08,
      layers: [
        { mat: 'forestFloor', scale: 0.0019, threshold: 0.0, softness: 0.38 },
        { mat: 'trail', scale: 0.0042, threshold: 0.28, softness: 0.2, offset: 17 },
      ],
    },
    props: [
      { name: 'pine', w: 14 },
      { name: 'birch', w: 5 },
      { name: 'rockMossy', w: 4 },
      { name: 'stump', w: 3 },
      { name: 'grass', w: 10 },
      { name: 'deadTree', w: 2 },
      { name: 'bones', w: 1.5 },
    ],
    landmarks: ['idol', 'brazier'],
    monsters: ['wolf', 'raider', 'wolf', 'shaman'],
    boss: 'wolfsvater',
    quota: 34,
    size: 2900,
    levelRange: [6, 13],
  },
  {
    id: 'bog',
    name: 'III. Великое болото',
    subtitle: 'Где топили жертвы',
    intro:
      'Торф, чёрная вода и блуждающие огни. Болотные мертвецы больше не лежат смирно.',
    ambience: 'bog',
    key: 36,
    terrain: {
      base: 'peat',
      wet: 0.3,
      layers: [
        { mat: 'bogWater', scale: 0.0015, threshold: 0.06, softness: 0.26 },
        { mat: 'moss', scale: 0.0036, threshold: 0.26, softness: 0.3, offset: 53 },
      ],
    },
    props: [
      { name: 'deadTree', w: 9 },
      { name: 'reeds', w: 7 },
      { name: 'idolLit', w: 1.6 },
      { name: 'bones', w: 1.8 },
      { name: 'rock', w: 2 },
      { name: 'stump', w: 2 },
    ],
    landmarks: ['idolLit', 'standingStone'],
    monsters: ['wraith', 'drowned', 'wraith', 'shaman'],
    boss: 'laume',
    quota: 40,
    size: 3000,
    levelRange: [13, 21],
  },
  {
    id: 'castle',
    name: 'IV. Орденский замок',
    subtitle: 'Мариенвердер, павший',
    intro:
      'Врата распахнуты. Братья всё ещё несут стражу — спустя десятилетия после смерти.',
    ambience: 'castle',
    key: 39,
    terrain: {
      base: 'flagstone',
      wet: 0.1,
      layers: [
        { mat: 'cobble', scale: 0.0021, threshold: 0.05, softness: 0.28 },
        { mat: 'trail', scale: 0.0044, threshold: 0.3, softness: 0.22, offset: 77 },
      ],
    },
    props: [
      { name: 'ruinWall', w: 8 },
      { name: 'ruinWallTall', w: 4 },
      { name: 'rock', w: 4 },
      { name: 'crate', w: 1.4 },
      { name: 'bones', w: 2.2 },
      { name: 'banner', w: 0.8 },
      { name: 'bannerRed', w: 0.4 },
    ],
    landmarks: ['brazier', 'banner', 'ruinWallTall'],
    monsters: ['skeleton', 'crossbowman', 'skeleton', 'revenant'],
    boss: 'hochmeister',
    quota: 46,
    size: 3000,
    levelRange: [21, 29],
  },
  {
    id: 'grove',
    name: 'V. Ромува, священная роща',
    subtitle: 'Дуб, который никто не срубит',
    intro:
      'Здесь поход кончается. Под священным дубом тебя не ждёт больше ни один человек.',
    ambience: 'grove',
    key: 34,
    terrain: {
      base: 'grove',
      wet: 0.12,
      layers: [
        { mat: 'moss', scale: 0.0018, threshold: 0.04, softness: 0.32 },
        { mat: 'forestFloor', scale: 0.0038, threshold: 0.24, softness: 0.28, offset: 91 },
      ],
    },
    props: [
      { name: 'oak', w: 4 },
      { name: 'standingStone', w: 5 },
      { name: 'idolLit', w: 2 },
      { name: 'rockMossy', w: 3 },
      { name: 'grass', w: 8 },
      { name: 'bones', w: 1.5 },
    ],
    landmarks: ['oakSacred', 'standingStone', 'idolLit'],
    monsters: ['shaman', 'revenant', 'wraith', 'raider'],
    boss: 'perkunas',
    quota: 52,
    size: 3100,
    levelRange: [29, 40],
  },
];

// ---------------------------------------------------------------------------
// Items
// ---------------------------------------------------------------------------

export const SLOTS = ['weapon', 'offhand', 'head', 'chest', 'hands', 'feet', 'ring', 'amulet'];

export const SLOT_NAMES = {
  weapon: 'Оружие',
  offhand: 'Nebenhand',
  head: 'Голова',
  chest: 'Грудь',
  hands: 'Руки',
  feet: 'Ноги',
  ring: 'Кольцо',
  amulet: 'Амулет',
};

export const ITEM_BASES = [
  { id: 'sword', slot: 'weapon', name: 'Орденский меч', dmg: [10, 16], icon: 'sword' },
  { id: 'falchion', slot: 'weapon', name: 'Фальшион', dmg: [13, 19], icon: 'sword' },
  { id: 'warhammer', slot: 'weapon', name: 'Боевой молот', dmg: [16, 24], icon: 'mace' },
  { id: 'bow', slot: 'weapon', name: 'Тисовый лук', dmg: [9, 20], icon: 'bow' },
  { id: 'staff', slot: 'weapon', name: 'Янтарный посох', dmg: [8, 18], icon: 'staff' },
  { id: 'shield', slot: 'offhand', name: 'Орденский щит', armor: 12, icon: 'shield' },
  { id: 'buckler', slot: 'offhand', name: 'Баклер', armor: 7, icon: 'shield' },
  { id: 'tome', slot: 'offhand', name: 'Колдовская книга', armor: 4, icon: 'book' },
  { id: 'greathelm', slot: 'head', name: 'Топфхельм', armor: 10, icon: 'helm' },
  { id: 'kettle', slot: 'head', name: 'Железная шляпа', armor: 8, icon: 'helm' },
  { id: 'hood', slot: 'head', name: 'Кожаный капюшон', armor: 5, icon: 'helm' },
  { id: 'plate', slot: 'chest', name: 'Латный доспех', armor: 20, icon: 'chest' },
  { id: 'mail', slot: 'chest', name: 'Кольчуга', armor: 15, icon: 'chest' },
  { id: 'robe', slot: 'chest', name: 'Колдовское облачение', armor: 8, icon: 'chest' },
  { id: 'gauntlets', slot: 'hands', name: 'Латные рукавицы', armor: 7, icon: 'glove' },
  { id: 'gloves', slot: 'hands', name: 'Кожаные перчатки', armor: 4, icon: 'glove' },
  { id: 'sabatons', slot: 'feet', name: 'Железные башмаки', armor: 7, icon: 'boot' },
  { id: 'boots', slot: 'feet', name: 'Дорожные сапоги', armor: 4, icon: 'boot' },
  { id: 'ring', slot: 'ring', name: 'Серебряное кольцо', armor: 0, icon: 'ring' },
  { id: 'amulet', slot: 'amulet', name: 'Янтарный амулет', armor: 0, icon: 'amulet' },
];

/** Affix pool. `t` scales with item level. */
export const AFFIXES = [
  { id: 'might', name: 'Силы', stat: 'might', t: [1, 3], w: 10 },
  { id: 'agility', name: 'Быстроты', stat: 'agility', t: [1, 3], w: 10 },
  { id: 'vigor', name: 'Стойкости', stat: 'vigor', t: [1, 3], w: 10 },
  { id: 'spirit', name: 'Духа', stat: 'spirit', t: [1, 3], w: 10 },
  { id: 'life', name: 'Жизни', stat: 'life', t: [8, 22], w: 9 },
  { id: 'armor', name: 'Защиты', stat: 'armor', t: [3, 9], w: 9 },
  { id: 'dmgPct', name: 'Гнева', stat: 'dmgPct', t: [0.03, 0.08], pct: true, w: 8 },
  { id: 'critChance', name: 'Меткости', stat: 'critChance', t: [0.012, 0.032], pct: true, w: 6 },
  { id: 'critDmg', name: 'Жестокости', stat: 'critDmg', t: [0.08, 0.22], pct: true, w: 6 },
  { id: 'attackSpeed', name: 'Спешки', stat: 'attackSpeed', t: [0.02, 0.06], pct: true, w: 6 },
  { id: 'moveSpeed', name: 'Ветра', stat: 'moveSpeed', t: [0.02, 0.05], pct: true, w: 5 },
  { id: 'lifeOnHit', name: 'Жажды крови', stat: 'lifeOnHit', t: [0.6, 2.2], w: 6 },
  { id: 'resourceRegen', name: 'Выносливости', stat: 'resourceRegen', t: [0.6, 2.0], w: 5 },
  { id: 'thorns', name: 'Шипов', stat: 'thorns', t: [2, 7], w: 4 },
  { id: 'goldFind', name: 'Купца', stat: 'goldFind', t: [0.05, 0.16], pct: true, w: 4 },
  { id: 'coldRes', name: 'Мороза', stat: 'coldRes', t: [0.02, 0.06], pct: true, w: 4 },
];

export const UNIQUES = [
  {
    id: 'winterMantle',
    name: 'Зимний плащ великого магистра',
    base: 'plate',
    minLevel: 8,
    flavour: '«Он не мёрз. Он давно перестал чувствовать.»',
    stats: { armor: 40, vigor: 8, coldRes: 0.25, thorns: 14 },
    power: 'frostNova',
    powerText: 'Когда тебя ранят, воздух вокруг застывает.',
  },
  {
    id: 'amberHeart',
    name: 'Янтарное сердце',
    base: 'amulet',
    minLevel: 6,
    flavour: '«Солнечный свет, утонувший в смоле тысячу лет назад.»',
    stats: { spirit: 12, dmgPct: 0.16, lifeOnHit: 4 },
    power: 'amberBurst',
    powerText: 'Убийства взрывают янтарные осколки.',
  },
  {
    id: 'wolfFang',
    name: 'Клык Волчьего отца',
    base: 'falchion',
    minLevel: 12,
    flavour: '«Охотника нашли. Не всего.»',
    stats: { might: 10, critChance: 0.09, critDmg: 0.5, attackSpeed: 0.12 },
    power: 'bleed',
    powerText: 'Критические удары пускают врагам кровь.',
  },
  {
    id: 'perkunasAxe',
    name: 'Клин Перкунаса',
    base: 'warhammer',
    minLevel: 22,
    flavour: '«У грома есть рукоять — если хватит смелости.»',
    stats: { might: 18, dmgPct: 0.24, critDmg: 0.4 },
    power: 'chainLightning',
    powerText: 'Удары перескакивают молнией на ближних врагов.',
  },
  {
    id: 'bogLantern',
    name: 'Фонари Лаумы',
    base: 'tome',
    minLevel: 16,
    flavour: '«Не иди за ним. За ним идут все.»',
    stats: { spirit: 14, armor: 22, resourceRegen: 4 },
    power: 'wisps',
    powerText: 'Два блуждающих огня кружат вокруг тебя и нападают.',
  },
  {
    id: 'ironFaith',
    name: 'Железная вера',
    base: 'shield',
    minLevel: 10,
    flavour: '«Крест выстоял, когда рука за ним давно сломалась.»',
    stats: { armor: 46, vigor: 10, thorns: 20 },
    power: 'bulwark',
    powerText: 'Ниже 35 % жизни весь урон по тебе вдвое меньше.',
  },
];

export const RARITIES = {
  common: { id: 'common', name: 'Обычная', affixes: [0, 0], color: PAL.rarity.common, w: 100 },
  magic: { id: 'magic', name: 'Магическая', affixes: [1, 2], color: PAL.rarity.magic, w: 42 },
  rare: { id: 'rare', name: 'Редкая', affixes: [3, 4], color: PAL.rarity.rare, w: 13 },
  unique: { id: 'unique', name: 'Уникальная', affixes: [0, 0], color: PAL.rarity.unique, w: 1.5 },
};

export const PREFIXES = [
  'Verrostetes', 'Geweihtes', 'Blutiges', 'Bernsteinernes', 'Frostiges', 'Uraltes',
  'Prußisches', 'Schamaitisches', 'Marienburger', 'Gebrochenes', 'Wölfisches', 'Torfschwarzes',
  'Silbernes', 'Sturmgeborenes', 'Verfluchtes', 'Geschmiedetes',
];

export const SUFFIX_PLACES = [
  'vom Haff', 'aus Romuva', 'von Marienwerder', 'aus dem Moor', 'der Rominte',
  'von der Nehrung', 'aus Königsberg', 'der Eiche', 'des Ordens', 'der Heide',
];

// ---------------------------------------------------------------------------
// Progression
// ---------------------------------------------------------------------------

export const MAX_LEVEL = 40;

export function xpForLevel(level) {
  // Tuned so a straight run through the five acts lands around level 30, and
  // the Eternal Hunt carries the last stretch to 40.
  return Math.round(46 * Math.pow(level, 1.55) + 30 * level);
}

export function monsterLevelFor(actIndex, progress) {
  const act = ACTS[actIndex];
  const [a, b] = act.levelRange;
  return Math.round(a + (b - a) * progress);
}
