// Generated by bjj/tools/base-room.mjs — do not edit by hand.
//
// The share of the base lean (BASE_LEAN in rig.js) each man can show in each
// position on the ground without putting himself into the other man: the
// largest fraction of it that adds no more than a centimetre to the deepest
// contact, in the pose and in the loops it holds through. A position that is
// not listed shows all of it.

export const BASE_ROOM = {
  CLOSED_GUARD: { A: 0.15, B: 1 },
  OPEN_GUARD: { A: 0.75, B: 1 },
  HALF_GUARD: { A: 0.15, B: 0.35 },
  SIDE_CONTROL: { A: 1, B: 0.75 },
  KNEE_ON_BELLY: { A: 1, B: 1 },
  MOUNT: { A: 1, B: 1 },
  BACK: { A: 0.15, B: 0.75 },
  TURTLE: { A: 0.45, B: 1 },
  RNC: { A: 1, B: 0.85 },
  ARMBAR: { A: 1, B: 1 },
  TRIANGLE: { A: 1, B: 1 },
  KIMURA: { A: 1, B: 1 },
  GUILLOTINE: { A: 1, B: 1 },
  ACROSS: { A: 0.4, B: 0.2 },
  MOUNT_ENTRY: { A: 1, B: 1 },
  SIDE_ENTRY: { A: 1, B: 0.9 },
  GUARD_ENTRY: { A: 0.25, B: 0.15 },
  GUARD_RECOVER: { A: 1, B: 0.55 },
  BACK_WORK: { A: 0.7, B: 0.8 },
  RNC_WORK: { A: 1, B: 1 },
  HALF_GUARD_WORK: { A: 0.15, B: 0.35 },
  MOUNT_WORK: { A: 1, B: 1 },
  SIDE_CONTROL_WORK: { A: 1, B: 0.75 },
  CLOSED_GUARD_WORK: { A: 0.15, B: 1 },
  OPEN_GUARD_WORK: { A: 0.75, B: 1 },
  KNEE_ON_BELLY_WORK: { A: 1, B: 1 },
  TURTLE_WORK: { A: 0.45, B: 0.1 },
  ARMBAR_WORK: { A: 1, B: 0.6 },
  TRIANGLE_WORK: { A: 0.85, B: 1 },
  KIMURA_WORK: { A: 1, B: 1 },
  GUILLOTINE_WORK: { A: 0, B: 1 },
  BACK_WORK2: { A: 0.15, B: 0.75 },
  RNC_WORK2: { A: 1, B: 0.85 },
  HALF_GUARD_WORK2: { A: 0.65, B: 1 },
  SIDE_CONTROL_WORK2: { A: 1, B: 0.6 },
  SIDE_CONTROL_X: { A: 0.85, B: 1 },
  MOUNT_X: { A: 1, B: 1 },
  BACK_X: { A: 1, B: 1 },
  CLOSED_GUARD_X: { A: 1, B: 0.65 },
  OPEN_GUARD_X: { A: 1, B: 0.8 },
  HALF_GUARD_X: { A: 1, B: 1 },
  TURTLE_X: { A: 1, B: 1 },
};
