// Generated by tools/build-solve.mjs — do not edit by hand.
//
// The heaviest and the lightest build the pose library holds with both men
// wearing it: no more than 1.5 cm added to or taken from the deepest
// contact between them, or to how far either is into the mat, in any pose or
// at any of blend-check's samples of any blend. See src/render/build.js.
//
//   heavy +11.8% of a man, light -11.2%
export const BUILD_ROOM = {
  heavy: { trunkW: 1.03, trunkD: 1.045, neck: 1.1, arm: 1.085, fore: 1.09, thigh: 1.06, shin: 1.075 },
  light: { trunkW: 0.96, trunkD: 0.96, neck: 0.905, arm: 0.915, fore: 0.905, thigh: 0.94, shin: 0.925 },
};
