// How much of the base each man can show in each position.
//
// The left thumb on the ground is weight and frames (match.js), and the rig
// shows it as a man gathering into the other one: the back rounds, the
// shoulders come forward, the chin goes down (BASE_LEAN, rig.js _life). A few
// degrees, the same for everybody — and in most positions that is a couple of
// centimetres of head and shoulders and nothing else. In a few it is a head
// put through a head: the turtle's working variant, the guillotine, the back.
// Measured at a full lean, the bottom man of TURTLE_WORK went from 5.7 cm of
// overlap to 11.3, and no set of angles is both visible in the open positions
// and safe in the tight ones.
//
// So each position gets its own share of the lean, found here rather than at
// runtime: the largest fraction of BASE_LEAN, per position and per man, that
// adds no more than ROOM_COST of depth to the deepest contact. Written to
// src/game/base-room.js, the way the arc solver writes arcs.js; the rig scales
// the thumb by it and crossfades it across a transition.
//
//   node bjj/tools/base-room.mjs           report
//   node bjj/tools/base-room.mjs --write   and write src/game/base-room.js

import { writeFileSync } from 'node:fs';
import { PairRig } from '../src/game/rig.js';
import { POSES, HOLD_LOOPS } from '../src/game/poses.js';
import { BASE_ROOM } from '../src/game/base-room.js';
import { BONE_INDEX } from '../src/render/skeleton.js';
import { Overlap } from '../src/game/collide.js';

const WRITE = process.argv.includes('--write');
// Centimetres of extra depth a full lean may add, in metres. pose-check's
// "living costs" line allows the whole live layer three and a half; the base
// is one thing on top of it and gets under a third of that.
export const ROOM_COST = 0.01;

// The table is what is being solved, so it is cleared for the solve.
for (const k of Object.keys(BASE_ROOM)) delete BASE_ROOM[k];

const rig = new PairRig();
rig.live = false;
const overlap = new Overlap();
const ids = Object.keys(POSES).filter((id) => POSES[id].ground && !POSES[id].refereeOnly);

// A held position is not the pose: it cycles out to its variants and back
// (HOLD_LOOPS), and the lean is held through all of it. Judged on the pose
// alone, the table let the closed guard's loop go four centimetres deeper
// with both men leaning at half (pose-check, "living costs"). So the depth is
// the deepest of the pose and the middle of every loop it is an end of.
const LOOPS = Object.entries(HOLD_LOOPS).flatMap(([p, l]) => l.map((v) => [p, v]));
function samplesFor(id) {
  const out = [[id, id, 1]];
  for (const [a, b] of LOOPS) {
    if (a !== id && b !== id) continue;
    for (const t of [0.25, 0.5, 0.75]) out.push([a, b, t]);
  }
  return out;
}
function depths(id, role, press) {
  return samplesFor(id).map(([a, b, t]) => {
    rig.press.A = rig.press.B = 0;
    rig.press[role] = press;
    rig.effort.A = rig.effort.B = 0;
    rig.slack.A = rig.slack.B = 0;
    rig.rewind();
    rig.plantFeet = true;
    rig.invalidate(a);
    rig.invalidate(b);
    rig.applyAt(a, b, t, 0.016);
    return overlap.measure(rig.skel.A, rig.skel.B).deepest;
  });
}
// What the lean adds, at the worst of those moments — each against itself,
// because a loop deeper than its pose would otherwise hide what the lean
// does to the pose.
const added = (flat, id, role, press) => Math.max(...depths(id, role, press).map((d, i) => d - flat[i]));

const out = {};
for (const id of ids) {
  out[id] = {};
  for (const role of ['A', 'B']) {
    const flat = depths(id, role, 0);
    let lo = 0, hi = 1;
    if (added(flat, id, role, 1) <= ROOM_COST) lo = 1;
    else {
      for (let k = 0; k < 7; k++) {
        const mid = (lo + hi) / 2;
        if (added(flat, id, role, mid) <= ROOM_COST) lo = mid; else hi = mid;
      }
    }
    out[id][role] = Math.floor(lo * 20) / 20;
  }
}
rig.press.A = rig.press.B = 0;

const tight = ids.filter((id) => out[id].A < 1 || out[id].B < 1);
for (const id of tight) console.log(`  ${id.padEnd(20)} A ${out[id].A.toFixed(2)}  B ${out[id].B.toFixed(2)}`);
console.log(`${ids.length} positions on the ground, ${tight.length} with less than a full lean`);

if (WRITE) {
  const lines = ids.map((id) => `  ${id}: { A: ${out[id].A}, B: ${out[id].B} },`);
  writeFileSync(new URL('../src/game/base-room.js', import.meta.url),
    `// Generated by bjj/tools/base-room.mjs — do not edit by hand.
//
// The share of the base lean (BASE_LEAN in rig.js) each man can show in each
// position on the ground without putting himself into the other man: the
// largest fraction of it that adds no more than a centimetre to the deepest
// contact, in the pose and in the loops it holds through. A position that is
// not listed shows all of it.

export const BASE_ROOM = {
${lines.join('\n')}
};
`);
  console.log('wrote src/game/base-room.js');
}
