// How deep each pose's own contact is.
//
// The rig takes the two men out of each other by whatever is past a line
// (rig._depenetrate), and the line cannot be one number: a pose is allowed
// the contact it declares — a closed guard holds its man at nine centimetres,
// the back at ten — and pushing a held position apart in its own breathing
// cycle is a pulse, the same reason the blanket gap was taken off hold loops.
// So the line in flight is never below what the two poses at its ends already
// have, and this measures that, once, the way base-room.mjs measures the lean:
// the deepest overlap of each pose with the rig's own correction off.
//
//   node bjj/tools/contact-room.mjs           report
//   node bjj/tools/contact-room.mjs --write   and write src/game/contact-room.js

import { writeFileSync } from 'node:fs';

// The table is measured with the rig's own correction off — it is what that
// correction is measured against.
process.env.BJJ_DEPEN = '0';
const { PairRig } = await import('../src/game/rig.js');
import { POSES } from '../src/game/poses.js';
import { Overlap } from '../src/game/collide.js';

const WRITE = process.argv.includes('--write');

const rig = new PairRig();
rig.live = false;
const overlap = new Overlap();
const rows = [];
for (const id of Object.keys(POSES)) {
  if (POSES[id].refereeOnly) continue;
  rig.effort.A = rig.effort.B = 0;
  rig.slack.A = rig.slack.B = 0;
  rig.rewind();
  rig.applyAt(id, id, 1, 0.016);
  rows.push([id, overlap.measure(rig.skel.A, rig.skel.B).deepest]);
}
for (const [id, d] of rows) console.log(`${id.padEnd(22)} ${(d * 100).toFixed(1)} cm`);

if (WRITE) {
  const body = rows.map(([id, d]) => `  ${id}: ${(+d.toFixed(3))},`).join('\n');
  writeFileSync(new URL('../src/game/contact-room.js', import.meta.url),
    `// Generated by bjj/tools/contact-room.mjs — do not edit by hand.\n//\n` +
    `// The deepest overlap of each pose as authored, in metres: the contact it\n` +
    `// declares, below which the rig never pushes the two of them apart\n` +
    `// (rig._depenetrate).\n\nexport const CONTACT_ROOM = {\n${body}\n};\n`);
  console.log('\nwrote src/game/contact-room.js');
}
