// Export the rigged fighter as an OBJ, in a pose an auto-rigger will accept.
//
//   node bjj/tools/export-obj.mjs --out bjj/art/upload/judoka-apose.obj
//
// Written for one purpose: Mixamo's Upload Character. Its auto-rigger wants a
// single humanoid, limbs clear of the body, and it does not read .glb — so the
// montage the sculpt arrived in is wrong on three counts at once.
//
// The pose is the interesting part. An auto-rigger places joints by looking at
// the silhouette, so arms hanging against the ribs are the worst case: it
// cannot see where the torso stops and the sleeve starts. The sculpt is already
// rigged *here*, though — so it can be posed into a clean A-pose first, with
// this rig, and handed over in the shape the rigger wants. The result comes back
// with weights better than the ones computed here, on a mesh that was posed by
// the ones computed here, which is a fair trade.

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { dirname } from 'path';
import { decodeFighter } from '../src/render/asset.js';
import { Skeleton, BONE_INDEX } from '../src/render/skeleton.js';
import { qEuler } from '../src/core/m4.js';

const argv = process.argv.slice(2);
const flag = (n, d) => {
  const i = argv.indexOf('--' + n);
  return i >= 0 ? argv[i + 1] : d;
};
const IN = flag('in', 'bjj/assets/fighter.bin');
const OUT = flag('out', 'bjj/art/upload/judoka-apose.obj');
const SPREAD = +flag('spread', 55); // degrees the arms come away from the body

const raw = readFileSync(IN);
const mesh = decodeFighter(raw.buffer.slice(raw.byteOffset, raw.byteOffset + raw.length));
const n = mesh.pos.length / 3;

// The A-pose. Arms out and straight, legs apart, everything else at rest —
// nothing here is a fighting stance, and that is the point.
const sk = new Skeleton();
const set = (bone, x, y, z) => qEuler(sk.local[BONE_INDEX[bone]], x, y, z);
set('armL', 0, 0, SPREAD);
set('armR', 0, 0, -SPREAD);
set('foreL', 0, 0, 4);
set('foreR', 0, 0, -4);
set('handL', 0, 0, 6);
set('handR', 0, 0, -6);
set('thighL', 0, 0, 7);
set('thighR', 0, 0, -7);
set('clavL', 0, 0, 4);
set('clavR', 0, 0, -4);
sk.pose();
sk.finishSkin();

const skin = sk.skin;
const out = [];
const P = new Float64Array(n * 3);
const N = new Float64Array(n * 3);
for (let v = 0; v < n; v++) {
  const b0 = mesh.bone[v * 2] * 16, b1 = mesh.bone[v * 2 + 1] * 16;
  const w0 = mesh.wt[v * 2], w1 = mesh.wt[v * 2 + 1];
  const m = new Float64Array(16);
  for (let k = 0; k < 16; k++) m[k] = skin[b0 + k] * w0 + skin[b1 + k] * w1;
  const x = mesh.pos[v * 3], y = mesh.pos[v * 3 + 1], z = mesh.pos[v * 3 + 2];
  P[v * 3] = m[0] * x + m[4] * y + m[8] * z + m[12];
  P[v * 3 + 1] = m[1] * x + m[5] * y + m[9] * z + m[13];
  P[v * 3 + 2] = m[2] * x + m[6] * y + m[10] * z + m[14];
  const nx = mesh.nrm[v * 3], ny = mesh.nrm[v * 3 + 1], nz = mesh.nrm[v * 3 + 2];
  const tx = m[0] * nx + m[4] * ny + m[8] * nz;
  const ty = m[1] * nx + m[5] * ny + m[9] * nz;
  const tz = m[2] * nx + m[6] * ny + m[10] * nz;
  const l = Math.hypot(tx, ty, tz) || 1;
  N[v * 3] = tx / l;
  N[v * 3 + 1] = ty / l;
  N[v * 3 + 2] = tz / l;
}

// Auto-riggers expect centimetres far more often than metres, and a character
// a metre and a half tall in "units" is ambiguous. Scale so the numbers read as
// centimetres, which is what Mixamo's own rigs use.
const SCALE = 100;
out.push('# Jiu-Jitsu fighter, A-pose, for auto-rigging');
out.push('# generated by bjj/tools/export-obj.mjs — units are centimetres');
out.push('o Fighter');
for (let v = 0; v < n; v++) {
  out.push(`v ${(P[v * 3] * SCALE).toFixed(3)} ${(P[v * 3 + 1] * SCALE).toFixed(3)} ${(P[v * 3 + 2] * SCALE).toFixed(3)}`);
}
for (let v = 0; v < n; v++) {
  out.push(`vn ${N[v * 3].toFixed(4)} ${N[v * 3 + 1].toFixed(4)} ${N[v * 3 + 2].toFixed(4)}`);
}
for (let t = 0; t < mesh.count; t += 3) {
  const a = mesh.idx[t] + 1, b = mesh.idx[t + 1] + 1, c = mesh.idx[t + 2] + 1;
  out.push(`f ${a}//${a} ${b}//${b} ${c}//${c}`);
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, out.join('\n') + '\n');

let lo = [1e9, 1e9, 1e9], hi = [-1e9, -1e9, -1e9];
for (let v = 0; v < n; v++) {
  for (let k = 0; k < 3; k++) {
    lo[k] = Math.min(lo[k], P[v * 3 + k] * SCALE);
    hi[k] = Math.max(hi[k], P[v * 3 + k] * SCALE);
  }
}
console.log(
  `wrote ${OUT}\n  ${n} verts, ${mesh.count / 3} tris, ` +
  `${(Buffer.byteLength(out.join('\n')) / 1024 / 1024).toFixed(1)} MB\n  ` +
  `bounds ${lo.map((v) => v.toFixed(0)).join(', ')} .. ${hi.map((v) => v.toFixed(0)).join(', ')} cm ` +
  `(${(hi[1] - lo[1]).toFixed(0)} cm tall, ${(hi[0] - lo[0]).toFixed(0)} cm across)`
);
