// Which pose to curve a transition through.
//
// A waypoint that swells in the middle can shove two bodies apart; it cannot
// route a limb around one. Taking side control from the back means a leg has to
// come out from between the other man's and travel round him, and every point
// on the straight line between those two tangles has it going through him — so
// the answer is not a bigger shove, it is a different path.
//
// The library already contains fifteen tangles that people actually get into,
// and for most of these the way round is one of them. This tries every pose as
// the middle control point of a quadratic and keeps the one that helps most,
// which is both cheaper and more honest than authoring an in-between by hand:
// if none of them helps, it says so and the transition keeps its straight line.
//
//   node bjj/tools/via-pick.mjs            report
//   node bjj/tools/via-pick.mjs --write    write VIAS into src/game/arcs.js

import { readFileSync, writeFileSync } from 'node:fs';
import { PairRig } from '../src/game/rig.js';
import { POSITION_IDS } from '../src/game/poses.js';
import { VIAS } from '../src/game/arcs.js';
import { TRANSITIONS } from '../src/game/positions.js';
import { BONE_INDEX } from '../src/render/skeleton.js';
import { Overlap } from '../src/game/collide.js';
import { JUDGE_STEPS } from './grid.mjs';

const WRITE = process.argv.includes('--write');
// The same grid blend-check judges on — thirteen stepped over the very
// crossings this tool exists to route around. See grid.mjs.
const STEPS = JUDGE_STEPS;
// Only transitions this bad are worth bending; below it the straight line is
// fine and a curve is a change nobody asked for.
const TRIGGER = 0.11;
// And a curve has to actually pay for itself.
const GAIN = 0.02;
// How far apart the two of them may drift on the way. Without this every
// transition picks STANDING, because standing solves interpenetration perfectly
// by having the two fighters half a metre apart — which on the way from mount
// to half guard reads as both of them being yanked to their feet and put back.
const TOGETHER = 0.30;
const READ = ['headTop', 'handL', 'handR', 'footL', 'footR', 'hips', 'chest'];

const rig = new PairRig();
const overlap = new Overlap();

function walk(from, to) {
  let worst = 0, apart = 0;
  for (let i = 1; i < STEPS - 1; i++) {
    rig.effort.A = rig.effort.B = 0;
    rig.slack.A = rig.slack.B = 0;
    rig.time = 0;
    rig.apply(from, to, i / (STEPS - 1), 0.016);
    const ov = overlap.measure(rig.skel.A, rig.skel.B);
    if (ov.deepest > worst) worst = ov.deepest;

    let closest = 1e9;
    for (const a of READ) {
      const ma = rig.skel.A.world[BONE_INDEX[a]];
      for (const b of READ) {
        const mb = rig.skel.B.world[BONE_INDEX[b]];
        const d = Math.hypot(ma[12] - mb[12], ma[13] - mb[13], ma[14] - mb[14]);
        if (d < closest) closest = d;
      }
    }
    if (closest > apart) apart = closest;
  }
  return { worst, apart };
}

const keys = [];
const seen = new Set();
for (const tr of TRANSITIONS) {
  const key = `${tr.from}>${tr.to}`;
  if (tr.from === tr.to || seen.has(key)) continue;
  seen.add(key);
  keys.push(key);
}

// Positions only. A held position's working variant is the same tangle with
// a hip moved, so routing through one is routing through the pose you are
// already at — twenty more candidates that cannot help and can win by noise.
const poses = POSITION_IDS;
const chosen = {};
for (const key of keys) {
  const [from, to] = key.split('>');
  delete VIAS[key];
  const straight = walk(from, to).worst;
  if (straight < TRIGGER) continue;

  let best = null, bestWorst = straight;
  for (const p of poses) {
    if (p === from || p === to) continue;
    VIAS[key] = p;
    const m = walk(from, to);
    if (m.apart > TOGETHER) continue;   // they came apart on the way
    if (m.worst < bestWorst - GAIN) { bestWorst = m.worst; best = p; }
  }
  if (best) {
    VIAS[key] = best;
    chosen[key] = best;
    console.log(
      `  ${key.padEnd(28)} ${(straight * 100).toFixed(0).padStart(3)}cm -> ` +
      `${(bestWorst * 100).toFixed(0).padStart(3)}cm   via ${best}`
    );
  } else {
    delete VIAS[key];
    console.log(`! ${key.padEnd(28)} ${(straight * 100).toFixed(0).padStart(3)}cm   no pose helps`);
  }
}

console.log(`\n${Object.keys(chosen).length} transitions curved`);

if (WRITE) {
  const path = new URL('../src/game/arcs.js', import.meta.url);
  let src = readFileSync(path, 'utf8');
  const body = Object.entries(chosen)
    .sort((a, b) => (a[0] < b[0] ? -1 : 1))
    .map(([k, v]) => `  '${k}': '${v}',`)
    .join('\n');
  const block = `// Generated by bjj/tools/via-pick.mjs.
//
// A transition listed here is a curve rather than a straight line: the pose
// named is the middle control point of a quadratic, pulled to half weight at
// the midpoint of the blend. These are the ones where no amount of shoving
// helps, because a limb has to travel around a body rather than through it.
export const VIAS = {
${body}
};`;
  src = src.replace(/(\/\/ Generated by bjj\/tools\/via-pick\.mjs[\s\S]*?\n\};|export const VIAS = \{[\s\S]*?\};)/, block);
  writeFileSync(path, src);
  console.log(`wrote ${Object.keys(chosen).length} vias into src/game/arcs.js`);
}
